### PR TITLE
Generate CSRs

### PR DESCRIPTION
**Pull request by goetzk**
Hi,
Would you be interested in/willing to merge functionality generate CSRs?
The included code works for no-ops but has a bug when trying to generate the CSR. If you are interested in merging it I will put some effort in to fixing the problem :)

(Commit says its from Sept 2014. It isn't.)
thanks,

### CODE REVIEW

**Comment by franklinkim** [comment]
hi, sure! will be on the road the next couple of days so don't worry if you complete the prs and don't get any from me :)

**Comment by franklinkim** [comment]
wanted to say: ... any feedback from me.

**Comment by goetzk** [comment]
I believe this one to be ready, CI permitting :)

**Comment by franklinkim** [comment]
THX, merged in release 1.9.0

**Pull request closed without merging**
